# Fake News Classification using LSTM

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [4]:
df.describe()

                 id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
id        20800 non-null int64
title     20242 non-null object
author    18843 non-null object
text      20761 non-null object
label     20800 non-null int64
dtypes: int64(2), object(3)
memory usage: 812.6+ KB

In [6]:
df=df.dropna()#drop the Nan Values

In [7]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [75]:
df.tail()

,id,title,author,text,label
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [11]:
df2= df.drop(['id'], axis = 1)

In [15]:
df2.head()

,title,author,text,label
0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [16]:
from sklearn import preprocessing

In [26]:
df2.dropna()

,title,author,text,label
0,7002,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,5380,Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,17017,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,119,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,7845,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,8142,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
7,2017,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
9,441,Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0
10,10630,Aaron Klein,"Organizing for Action, the activist group that...",0
11,1730,Chris Tomlinson,The BBC produced spoof on the “Real Housewives...,0
12,12553,Amando Flavio,The mystery surrounding The Third Reich and Na...,1
13,15904,Jason Ditz,Clinton Campaign Demands FBI Affirm Trump's Ru...,1
14,11911,AnotherAnnie,"Yes, There Are Paid Government Trolls On Socia...",1
15,7591,Jack Williams,Guillermo Barros Schelotto was not the first A...,0
16,16578,Michael Corkery and Stacy Cowley,The scandal engulfing Wells Fargo toppled its ...,0
17,1324,Starkman,A Caddo Nation tribal leader has just been fre...,1
18,5304,The Doc,FBI Closes In On Hillary! Posted on Home » Hea...,1
19,3109,Jeff Poor,Wednesday after Donald Trump’s press confere...,0
21,9728,Jerome Hudson,"Screenwriter Ryan Murphy, who has produced the...",0
22,12352,Pam Key,"Sunday on MSNBC’s “AM Joy,” actor and director...",0
24,820,Donald G. McNeil Jr. and Pam Belluck,Orders for abortion pills by women in seven La...,0
25,10443,Ira Helfand,Email \nIn an historic move the United Nations...,1
26,4892,Aaron Klein and Ali Waked,JERUSALEM — Islamic State sympathizers and ...,0
27,7309,Amanda Shea,Humiliated Hillary Tries To Hide What Camera C...,1
28,1255,Jim Dwyer,"Andrea Tantaros, a former Fox News host, charg...",0
29,7087,Mark Landler,Hillary Clinton sat in the hideaway study off ...,0
30,3105,Ian Hanchett,During a discussion of BuzzFeed’s story on a d...,0
32,6571,Steven Erlanger,LONDON — With their giddy celebrations of “...,0
33,13928,Clifford Krauss,"MIDLAND, Tex. — In the land where oil jobs ...",0
34,1974,"Leslie Picker, Danny Hakim and Michael J. de l...","Don Halcomb, a farmer in Adairville, Ky. is...",0
...,...,...,...,...
20766,11448,Penny Starr,President Donald Trump officially declared tod...,0
20767,5805,Activist Post,By Brandon Turbeville Anti-fluoridation activi...,1
20769,16366,Pakalert,source Add To The Conversation Using Facebook ...,1
20770,6482,Iron Sheik,Home › POLITICS | US NEWS › HUMA ABEDIN SWORE ...,1
20773,1685,Vicki Batts,Australia to hunt down anti-vax nurses and pro...,1
20774,6377,Liam Deacon,Aided by a politically correct culture of “tol...,0
20775,7207,Arnaldo Rodgers,‹ › Arnaldo Rodgers is a trained and educated ...,1
20776,15008,Jameson Parker,Donald Trump was rushed from a rally stage by ...,1
20777,4940,admin,"Breitbart October 26, 2016 \nAn editor of Aust...",1
20778,14649,Neil Irwin,There’s not much to say about the July jobs nu...,0
20779,3089,"Thomas D. Williams, Ph.D.","In many parts of the world, Christians gatheri...",0
20780,5703,Christine Hauser,"Early on Oct. 6, Erin was awakened by the so...",0
20781,14761,Heather Callaghan,By Brandon Turbeville When the DEA announced t...,1
20782,14170,The Doc,Home » Headlines » World News » The Fix Is In:...,1
20783,12686,Charles McDermid,Good morning. Here’s what you need to know: •...,0
20784,3637,Debbie Menon,Finian Cunningham has written extensively on...,1
20785,1302,Ann Coulter,The first sentence of Congress’ Obamacare repe...,0
20787,12668,Ian Mason,Former Deputy Attorney General Sally Yates dec...,0
20788,9186,Joe Clark,Google Pinterest Digg Linkedin Reddit Stumbleu...,1
20789,12907,Warner Todd Huston,"Senate Majority Leader Mitch McConnell (R, KY)...",0
20790,10288,Adam Shaw,U. S Ambassador to the United Nations Nikki Ha...,0
20791,8777,Daniel Greenfield,Lawyer Who Kept Hillary Campaign Chief Out of ...,1
20792,8146,John Hayward,Two suicide bombers attacked a bus station in ...,0
20793,7440,Robert Rich,Share This \nAlthough the vandal who thought i...,1
20794,15430,Lee Stranahan,Donald Trump took to Twitter Friday to praise ...,0
20795,11780,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,9893,Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,9152,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,9936,Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,16672,David Swanson,"David Swanson is an author, activist, journa...",1

In [27]:
df2.isnull().sum()

title     0
author    0
text      0
label     0
dtype: int64

In [28]:
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder()

In [29]:
# Encode labels in column 'species'. 
df2['title']= label_encoder.fit_transform(df2['title']) 
df2['title'].unique()

array([ 7002,  5380, 17017, ...,  9893,  9152,  9936], dtype=int64)

In [30]:
df2

,title,author,text,label
0,7002,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,5380,Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,17017,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,119,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,7845,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
5,8142,Daniel Nussbaum,"In these trying times, Jackie Mason is the Voi...",0
7,2017,Alissa J. Rubin,"PARIS — France chose an idealistic, traditi...",0
9,441,Megan Twohey and Scott Shane,A week before Michael T. Flynn resigned as nat...,0
10,10630,Aaron Klein,"Organizing for Action, the activist group that...",0
11,1730,Chris Tomlinson,The BBC produced spoof on the “Real Housewives...,0
12,12553,Amando Flavio,The mystery surrounding The Third Reich and Na...,1
13,15904,Jason Ditz,Clinton Campaign Demands FBI Affirm Trump's Ru...,1
14,11911,AnotherAnnie,"Yes, There Are Paid Government Trolls On Socia...",1
15,7591,Jack Williams,Guillermo Barros Schelotto was not the first A...,0
16,16578,Michael Corkery and Stacy Cowley,The scandal engulfing Wells Fargo toppled its ...,0
17,1324,Starkman,A Caddo Nation tribal leader has just been fre...,1
18,5304,The Doc,FBI Closes In On Hillary! Posted on Home » Hea...,1
19,3109,Jeff Poor,Wednesday after Donald Trump’s press confere...,0
21,9728,Jerome Hudson,"Screenwriter Ryan Murphy, who has produced the...",0
22,12352,Pam Key,"Sunday on MSNBC’s “AM Joy,” actor and director...",0
24,820,Donald G. McNeil Jr. and Pam Belluck,Orders for abortion pills by women in seven La...,0
25,10443,Ira Helfand,Email \nIn an historic move the United Nations...,1
26,4892,Aaron Klein and Ali Waked,JERUSALEM — Islamic State sympathizers and ...,0
27,7309,Amanda Shea,Humiliated Hillary Tries To Hide What Camera C...,1
28,1255,Jim Dwyer,"Andrea Tantaros, a former Fox News host, charg...",0
29,7087,Mark Landler,Hillary Clinton sat in the hideaway study off ...,0
30,3105,Ian Hanchett,During a discussion of BuzzFeed’s story on a d...,0
32,6571,Steven Erlanger,LONDON — With their giddy celebrations of “...,0
33,13928,Clifford Krauss,"MIDLAND, Tex. — In the land where oil jobs ...",0
34,1974,"Leslie Picker, Danny Hakim and Michael J. de l...","Don Halcomb, a farmer in Adairville, Ky. is...",0
...,...,...,...,...
20766,11448,Penny Starr,President Donald Trump officially declared tod...,0
20767,5805,Activist Post,By Brandon Turbeville Anti-fluoridation activi...,1
20769,16366,Pakalert,source Add To The Conversation Using Facebook ...,1
20770,6482,Iron Sheik,Home › POLITICS | US NEWS › HUMA ABEDIN SWORE ...,1
20773,1685,Vicki Batts,Australia to hunt down anti-vax nurses and pro...,1
20774,6377,Liam Deacon,Aided by a politically correct culture of “tol...,0
20775,7207,Arnaldo Rodgers,‹ › Arnaldo Rodgers is a trained and educated ...,1
20776,15008,Jameson Parker,Donald Trump was rushed from a rally stage by ...,1
20777,4940,admin,"Breitbart October 26, 2016 \nAn editor of Aust...",1
20778,14649,Neil Irwin,There’s not much to say about the July jobs nu...,0
20779,3089,"Thomas D. Williams, Ph.D.","In many parts of the world, Christians gatheri...",0
20780,5703,Christine Hauser,"Early on Oct. 6, Erin was awakened by the so...",0
20781,14761,Heather Callaghan,By Brandon Turbeville When the DEA announced t...,1
20782,14170,The Doc,Home » Headlines » World News » The Fix Is In:...,1
20783,12686,Charles McDermid,Good morning. Here’s what you need to know: •...,0
20784,3637,Debbie Menon,Finian Cunningham has written extensively on...,1
20785,1302,Ann Coulter,The first sentence of Congress’ Obamacare repe...,0
20787,12668,Ian Mason,Former Deputy Attorney General Sally Yates dec...,0
20788,9186,Joe Clark,Google Pinterest Digg Linkedin Reddit Stumbleu...,1
20789,12907,Warner Todd Huston,"Senate Majority Leader Mitch McConnell (R, KY)...",0
20790,10288,Adam Shaw,U. S Ambassador to the United Nations Nikki Ha...,0
20791,8777,Daniel Greenfield,Lawyer Who Kept Hillary Campaign Chief Out of ...,1
20792,8146,John Hayward,Two suicide bombers attacked a bus station in ...,0
20793,7440,Robert Rich,Share This \nAlthough the vandal who thought i...,1
20794,15430,Lee Stranahan,Donald Trump took to Twitter Friday to praise ...,0
20795,11780,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,9893,Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,9152,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,9936,Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,16672,David Swanson,"David Swanson is an author, activist, journa...",1

In [31]:
df2['author']= label_encoder.fit_transform(df2['author']) 
df2['author'].unique()

array([ 887,  858,  783, ...,  805, 1839, 2448], dtype=int64)

In [32]:
df2['text']= label_encoder.fit_transform(df2['text']) 
df2['text'].unique()

array([ 7109,  5593, 17003, ..., 13791,  9431,   430], dtype=int64)

In [33]:
df2.head(2)

   title  author  text  label
0   7002     887  7109      1
1   5380     858  5593      0

In [35]:
X= df2.drop(['label'], axis=True)

In [36]:
X

       title  author   text
0       7002     887   7109
1       5380     858   5593
2      17017     783  17003
3        119    1655  15469
4       7845    1396  11578
5       8142     864   7664
7       2017     192  10697
9        441    2360   2092
10     10630      39  10599
11      1730     711  13587
12     12553     223  14378
13     15904    1566   4386
14     11911     376  17202
15      7591    1499   6521
16     16578    2403  14512
17      1324    3281   1610
18      5304    3396   5647
19      3109    1593  16628
21      9728    1643  12547
22     12352    2758  13189
24       820    1000  10589
25     10443    1436   5430
26      4892      40   7997
27      7309     220   7177
28      1255    1662   2620
29      7087    2249   6824
30      3105    1415   5184
32      6571    3315   8446
33     13928     764   8934
34      1974    2103   4941
...      ...     ...    ...
20766  11448    2834  11401
20767   5805      49   3604
20769  16366    2753  17676
20770   6482    1438   7045
20773   1685    3536   2909
20774   6377    2106   2403
20775   7207     394  17980
20776  15008    1546   5059
20777   4940    3652   3500
20778  14649    2632  14687
20779   3089    3431   7581
20780   5703     723   5293
20781  14761    1360   3612
20782  14170    3396   7015
20783  12686     673   6370
20784   3637     951    500
20785   1302     303  14219
20787  12668    1420   5980
20788   9186    1694   6472
20789  12907    3578  12609
20790  10288      78  15215
20791   8777     856   8608
20792   8146    1725  15207
20793   7440    3072  12680
20794  15430    2083   5057
20795  11780    1643  11919
20796   9893     478  16856
20797   9152    2448  13791
20798   9936     131   9431
20799  16672     934    430

[18285 rows x 3 columns]

In [37]:
y=df2.label

In [38]:
y

0        1
1        0
2        1
3        1
4        1
5        0
7        0
9        0
10       0
11       0
12       1
13       1
14       1
15       0
16       0
17       1
18       1
19       0
21       0
22       0
24       0
25       1
26       0
27       1
28       0
29       0
30       0
32       0
33       0
34       0
        ..
20766    0
20767    1
20769    1
20770    1
20773    1
20774    0
20775    1
20776    1
20777    1
20778    0
20779    0
20780    0
20781    1
20782    1
20783    0
20784    1
20785    0
20787    0
20788    1
20789    0
20790    0
20791    1
20792    0
20793    1
20794    0
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
Lg=LogisticRegression()

In [44]:
Lg.fit(X_train,y_train)

C:\Users\vishal\AppData\Local\Continuum\anaconda3\envs\data_S\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
Lg.score(X_test,y_test)

0.5940347970173985

In [49]:
df.tail()

,id,title,author,text,label
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [73]:
df2.head()

   title  author   text  label
0   7002     887   7109      1
1   5380     858   5593      0
2  17017     783  17003      1
3    119    1655  15469      1
4   7845    1396  11578      1

In [74]:
a=Lg.predict([[119,1655,15469]])

In [75]:
if a==0:
    print("fake")
else:
    print("real")

fake